version: '3.5'
networks:
  default:
    external:
      name: nginx-proxy
  frontend:
    external: true
  backend:
    external: true
  local:
    internal: true
volumes:
  app:
    driver: local-persist
    driver_opts:
      mountpoint: ${PROJECT_HOME_DIR}
  app_logs_nginx:
    driver: local-persist
    driver_opts:
      mountpoint: ${PROJECT_HOME_DIR}/.docker/volumes/app_logs/nginx
  app_data_mysql:
    driver: local-persist
    driver_opts:
      mountpoint: ${PROJECT_HOME_DIR}/.docker/volumes/app_data/mysql
  app_data_composer:
    driver: local-persist
    driver_opts:
      mountpoint: ${PROJECT_HOME_DIR}/.docker/volumes/app_data/composer
  app_data_nginx:
    driver: local-persist
    driver_opts:
      mountpoint: ${PROJECT_HOME_DIR}/.docker/volumes/app_data/nginx
  ssh:
    driver: local-persist
    driver_opts:
      mountpoint: ${SSH_DIR}
  ssl:
    driver: local-persist
    driver_opts:
      mountpoint: ${SSL_DIR}
services:
# MYSQL
  mysql:
    environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: app
       MYSQL_USER: app
       MYSQL_PASSWORD: app
    build:
      context: ./.docker/services/mysql
      dockerfile: Dockerfile
    networks:
      - local
    ports:
      - "3366:3306"
    volumes:
      - app_data_mysql:/var/lib/mysql
    restart: always
# PHP
  php:
    build:
      context: ./.docker/services/php
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
        WORKDIR: ${PROJECT_HOME_DIR}
    networks:
      - frontend
      - local
    ports:
      - "8000:80"
    volumes:
      - app:/app
    restart: always
# NGINX
  nginx:
    build:
      context: ./.docker/services/nginx
      dockerfile: Dockerfile
      args:
        CERTDIR: ${CERT_DIR}
    networks:
      - frontend
      - backend
      - local
      - default
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - app:/app
      - app_logs_nginx:/app_logs
      - app_data_nginx:/app_data
      - ssl:/etc/ssl
    restart: always
# Composer
  composer:
    image: composer:latest
    environment:
       PW: /app
       COMPOSER_HOME: /tmp
    volumes:
      - app:/app
      - app_data_composer:/tmp
      - ssh:/root/.ssh